delete from rs.event;

LOAD DATA INFILE 'c:/Data/Retrosheet/CSVs/2018Event.csv' 
INTO TABLE rs.event 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE 'c:/Data/Retrosheet/CSVs/2017Event.csv' 
INTO TABLE rs.event 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'c:/Data/Retrosheet/CSVs/2016Event.csv' 
INTO TABLE rs.event 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'c:/Data/Retrosheet/CSVs/2015Event.csv' 
INTO TABLE rs.event 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'c:/Data/Retrosheet/CSVs/2014Event.csv' 
INTO TABLE rs.event 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'c:/Data/Retrosheet/CSVs/2013Event.csv' 
INTO TABLE rs.event 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'c:/Data/Retrosheet/CSVs/2012Event.csv' 
INTO TABLE rs.event 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'c:/Data/Retrosheet/CSVs/2011Event.csv' 
INTO TABLE rs.event 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'c:/Data/Retrosheet/CSVs/2010Event.csv' 
INTO TABLE rs.event 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;